#!/usr/bin/env python
import os, sys, subprocess

# Open the Node.js log file in the master branch folder
master_path = os.path.join('..', 'master')
logfile = open(os.path.join(master_path, 'nodejs_sandbox.log'), 'a')

# Retrieve all branches in the repository...
process = subprocess.Popen(
                        'git log --pretty=oneline',
                        shell = True,
                        stdout = subprocess.PIPE)

out, err = process.communicate()
out = out.split('\n')

# Write the last commit message to the Node.js log file
logfile.write(out[0] + '\n')
logfile.close()

# Change working directory to the master branch folder
os.chdir(master_path)

# Add and commit the Node.js log file
command = 'git add -A;' + 'git commit -am \"Updating Node.js sandbox commit log...\"'
process = subprocess.Popen(
                        command,
                        shell = True).wait()
